import SwiftUI

struct TarotCard : Identifiable{
    var id : UUID = UUID()
    var name: String
    var imageName: String
    var description: String
    var category: String 
}



class TarotCardDataService {
    static let shared = TarotCardDataService()
    
    let tarotCards: [TarotCard]
    
    
    init() {
        self.tarotCards = [
            TarotCard(name: "the Fool", imageName: "protagonist1", description: "The Fool archetype in Tarot represents new beginnings, innocence, spontaneity, and a free-spirited nature.\n\nAs a protagonist archetype, the Fool is often depicted as a young, carefree individual setting out on a journey or adventure, oblivious to the challenges and dangers ahead.", category: "prot"),
            TarotCard(name: "the Magician", imageName: "protagonist2", description: "The Magician is a charismatic and resourceful individual who harnesses their talents and skills to achieve their goals.\n\nThey possess a deep understanding of the inner workings of the universe and are adept at channeling energy to bring their visions into reality. Their journey is one of self-discovery and empowerment, as they learn to tap into their full potential and embrace their talents.", category: "prot"),
            TarotCard(name: "the High Priestess", imageName: "protagonist3", description: "the High Priestess is a deeply introspective and intuitive individual who navigates the world with grace and intuition.\n\nShe possesses a profound connection to the subconscious mind and the unseen realms. The High Priestess protagonist often embarks on a journey of self-discovery and spiritual awakening, guided by her inner voice and intuition.", category: "prot"),
            TarotCard(name: "the Empress", imageName: "protagonist4", description: "The Empress is a nurturing and compassionate individual who fosters growth and prosperity in her surroundings.\n\n She is deeply connected to the natural world and possesses a profound appreciation for beauty and creativity whether it jouney could evolve in cultivating relationships, birthing new ideas, or fostering growth in her community.", category: "prot"),
            TarotCard(name: "the Emperor", imageName: "protagonist5", description: "The Emperor is a powerful and disciplined individual who seeks to establish order and structure in their world.\n\n They are decisive and assertive, commanding respect and loyalty from those around them. The Emperor protagonist often embarks on a journey of responsibility. They are guided by principles of fairness and justice, striving to create a society where everyone can thrive.", category: "prot"),
            TarotCard(name: "the Hierophant", imageName: "protagonist6", description: "The Hierophant is a wise and devout individual who seeks to uphold and transmit the teachings of their faith or tradition.\n\nThey are deeply rooted in their beliefs and values, serving as a spiritual leader and mentor to their community. The Hierophant protagonist often embarks on a journey of spiritual exploration and enlightenment and may face challenges that test their faith.", category: "prot"),
            TarotCard(name: "the Hermit", imageName: "protagonist7", description: "the Hermit is a solitary and contemplative individual who seeks truth and enlightenment through introspection and self-discovery. They withdraw from the distractions of the outside world to focus on their journey.\n\nThe Hermit protagonist often embarks on a journey of self-exploration and spiritual awakening, guided by their inner light, navigating the darkness of the unknown.", category: "prot"),
            
            TarotCard(name: "the Fool", imageName: "protagonist1", description: "As an antagonist archetype, the Fool in Tarot takes on a different role, embodying recklessness, impulsivity, and folly.\n\nThe Fool antagonist may disrupt the lives of others through their irresponsible actions, causing chaos and destruction. They may be portrayed as someone who refuses to learn from past mistakes, repeating patterns of behavior with disastrous results. ", category: "ant"),
            TarotCard(name: "the Magician", imageName: "protagonist2", description: "The Magician represents manipulation, deceit, and abuse of power.\n\nThis version of the Magician is cunning and manipulative, using their abilities to deceive and exploit others for personal gain. The Magician antagonist is often portrayed as a mastermind behind complex schemes or as a charismatic charlatan who deceives others with false promises.", category: "ant"),
            TarotCard(name: "the High Priestess", imageName: "protagonist3", description: "The High Priestess is enigmatic and inscrutable, using her intuitive powers to manipulate and control others for her own nefarious purposes.\n\nShe may operate behind the scenes, pulling strings and orchestrating events to achieve her goals without revealing her true intentions. The High Priestess antagonist is often portrayed as a formidable and mischievous adversary.", category: "ant"),
            TarotCard(name: "the Empress", imageName: "protagonist4", description: "The Empress is possessive and domineering, seeking to exert her influence over others and maintain control at all costs.\n\nShe may use her facade to manipulate and exploit those around her, stifling their independence and autonomy in the name of protection and care. The Empress antagonist is often portrayed as a formidable force who seeks to impose her will upon others.", category: "ant"),
            TarotCard(name: "the Emperor", imageName: "protagonist5", description: "The Emperor is authoritarian and domineering, seeking to impose their will upon others through force and intimidation.\n\nThey view themselves as the supreme authority, wielding their power to maintain their grip on power. The Emperor antagonist is often portrayed as a ruthless dictator or tyrant who rules through fear and manipulation and their actions may lead to rebellion and unrest.", category: "ant"),
            TarotCard(name: "the Hierophant", imageName: "protagonist6", description: "the Hierophant represents dogma, rigidity, and spiritual oppression. This version of the Hierophant is authoritarian and controlling, seeking to impose their beliefs and values upon others through force and coercion.\n\nThey view themselves as the ultimate authority, wielding their power to suppress dissent and maintain their hold on their followers. ", category: "ant"),
            TarotCard(name: "the Hermit", imageName: "protagonist7", description: "This version of the Hermit is withdrawn and reclusive, escaping from their problems or responsibilities.\n\nThey may wallow in self-pity, unable or unwilling to confront the challenges they face. The Hermit antagonist may also embody a sense of resentment towards the world, leading to further isolation and alienation from others, as they push away those who help them.", category: "ant"),
            
            TarotCard(name: "the Fool", imageName: "protagonist1", description: "As a deuteragonist archetype, the Fool in Tarot embodies a complex and multi-dimensional character who serves as a companion or foil to the main protagonist.\n\nThe Fool deuteragonist may possess a deeper understanding of life's complexities despite their outward appearance serving as a catalyst for growth in the main character, pushing them out of their comfort zone.", category: "deut"),
            TarotCard(name: "the Magician", imageName: "protagonist2", description: "the Magician embodies mentorship, guidance, and transformation.\n\nThey serve as a wise and enigmatic figure who assists the main protagonist on their journey of self-discovery and growth. The Magician deuteragonist possesses profound knowledge and insight into the workings of the universe, which they share with the protagonist to help them unlock their potential.", category: "deut"),
            TarotCard(name: "the High Priestess", imageName: "protagonist3", description: "The High Priestess embodies guidance, wisdom, and inner illumination.\n\nShe serves as a mentor and confidante to the main protagonist, offering insight and support on their journey of self-discovery and spiritual growth. The High Priestess deuteragonist possesses and shares a deep understanding of the mysteries of the universe, helping the protagonist navigate the challenges they face.", category: "deut"),
            TarotCard(name: "the Empress", imageName: "protagonist4", description: "The Empress embodies nurturing guidance, fertility, and maternal wisdom.\n\nShe serves as a mentor and protector to the main protagonist, offering support and guidance on their journey of growth and self-discovery. The Empress deuteragonist possesses a deep connection to the natural world and a profound understanding of the cycles of life and growth. ", category: "deut"),
            TarotCard(name: "the Emperor", imageName: "protagonist5", description: "The Emperor embodies wisdom, guidance, and paternal authority. He serves as a mentor and protector to the main protagonist, offering guidance and support on their journey of growth and self-discovery.\n\nThe Emperor deuteragonist possesses a deep understanding of leadership, imparting his knowledge and wisdom to the protagonist as they navigate the challenges they face.", category: "deut"),
            TarotCard(name: "the Hierophant", imageName: "protagonist6", description: "The Hierophant embodies wisdom, guidance, and spiritual mentorship. They serve as a mentor and teacher to the main protagonist.\n\nThe Hierophant deuteragonist possesses deep knowledge and understanding of spiritual matters, sharing their wisdom with the protagonist in his journey. They provide a moral compass for the protagonist, helping them to discern right from wrong. ", category: "deut"),
            TarotCard(name: "the Hermit", imageName: "protagonist7", description: "the Hermit embodies wisdom, guidance, and spiritual mentorship. They serve as a guide to the main protagonist.\n\nThe Hermit deuteragonist possesses deep knowledge and understanding of the inner workings of the psyche, sharing their wisdom and insights with the protagonist as they navigate the challenges they face.", category: "deut"),
            
            TarotCard(name: "the Lovers", imageName: "act1", description: "In the first act, the Lovers are introduced as two individuals who meet unexpectedly. Their initial encounter is marked by a sense of attraction and curiosity, drawing them together despite their differences.", category: "act1"),
            TarotCard(name: "the Wheel of Fortune", imageName: "act4", description: "In the first act, characters encounter the Wheel of Fortune, a symbol of fate and destiny. They may stumble upon it unexpectedly or seek it out in a moment of need. Characters are confronted with the realization that their lives are subject to the whims of destiny, and they must embrace the changes that lie ahead.", category: "act1"),
            TarotCard(name: "Death", imageName: "act7", description: "In the first act, characters encounter Death, a symbol of transformation and endings. They may face a significant loss or experience a dramatic change that marks the beginning of a new chapter in their lives. The presence of Death signals the end of a familiar era and the start of something unknown", category: "act1"),
            TarotCard(name: "the Devil", imageName: "act8", description: "In the first act, characters encounter The Devil, a symbol of temptation, bondage, and illusion. They may be lured into a situation or relationship that promises pleasure or fulfillment but ultimately leads to entrapment and enslavement. Characters find themselves trapped by their own desires or external influences, unable to break free from the chains that bind them.", category: "act1"),
            TarotCard(name: "the Tower", imageName: "act9", description: "In the first act, characters encounter The Tower, a symbol of sudden upheaval and destruction. They may experience a sudden and unexpected crisis that shakes the very foundations of their world. The stability they once relied upon is shattered, leaving chaos and uncertainty in its wake.", category: "act1"),
            TarotCard(name: "the Star", imageName: "act10", description: "In the first act, characters encounter The Star, a symbol of hope, inspiration, and guidance. They find themselves at a moment of transition or uncertainty, seeking direction and clarity in their lives. Characters are drawn to the light of The Star, feeling a sense of hope and optimism as they embark on a journey of self-discovery and renewal.", category: "act1"),
            TarotCard(name: "the Sun", imageName: "act11", description: "In the first act, characters encounter The Sun, a symbol of radiance, vitality, and joy. They bask in the warm glow of The Sun's light, feeling a sense of optimism and vitality wash over them. Characters experience a newfound sense of clarity and purpose as they embrace the energy of The Sun, feeling invigorated and uplifted by its presence.", category: "act1"),
            TarotCard(name: "the Moon", imageName: "act12", description: "In the first act, characters encounter The Moon, a symbol of mystery, illusion, and the subconscious mind. They find themselves navigating through a realm of shadows and uncertainty, where things may not be as they seem. Characters experience a sense of disorientation and confusion as they confront their deepest fears and insecurities.", category: "act1"),
            TarotCard(name: "the Judgment", imageName: "act13", description: "In the first act, characters encounter Judgment, a symbol of awakening, evaluation, and reckoning. They find themselves at a crossroads, facing a moment of truth and introspection. Characters are called to account for their actions and decisions, confronting the consequences of their past choices.", category: "act1"),
        
        
            TarotCard(name: "the Lovers", imageName: "act1", description: "The second act sees the Lovers facing challenges and obstacles that threaten to tear them apart. External forces, such as societal expectations or personal insecurities. They must confront these challenges head-on and make difficult choices that test the strength of their bond.", category: "act2"),
            TarotCard(name: "Strenght", imageName: "act3", description: "In the second act, characters embark on a journey of self-discovery and empowerment as they confront external challenges and adversity. They draw upon their inner strength to overcome obstacles and face their fears head-on. Through perseverance and determination, characters find the courage to stand up for what they believe in and push past their limitations.", category: "act2"),
            TarotCard(name: "the Wheel of Fortune", imageName: "act4", description: "Some moments may bring fortune and success, while others bring hardship and loss. Characters are tested by the unpredictable nature of the wheel, learning valuable lessons along the way. Despite the uncertainty, they persevere, knowing that each turn of the wheel brings them closer to their destiny.", category: "act2"),
            TarotCard(name: "the Justice", imageName: "act5", description: "In the second act, characters navigate a process of accountability and judgment as they seek to restore balance and rectify injustices. They confront their own actions and decisions, as well as those of others, and must weigh the consequences of their choices. Characters face moral dilemmas and ethical challenges as they strive to uphold principles of fairness and integrity.", category: "act2"),
            TarotCard(name: "the Hanged Man", imageName: "act6", description: "In the second act, characters undergo a process of introspection and enlightenment as they hang suspended in the liminal space of The Hanged Man. They gain a new perspective on their situation, seeing things from a different angle or viewpoint. Characters experience moments of clarity and insight as they detach from the distractions of the material world and connect with their inner wisdom.", category: "act2"),
            TarotCard(name: "Death", imageName: "act7", description: "In the second act, characters undergo a process of transformation and renewal. They confront their fears and insecurities, shedding old habits and beliefs that no longer serve them. Despite the pain and discomfort of letting go, characters begin to embrace the opportunity for growth and change.", category: "act2"),
            TarotCard(name: "the Devil", imageName: "act8", description: "In the second act, characters confront The Devil and the illusions that have kept them bound. They realize the destructive nature of their desires and the toxic patterns that have kept them trapped. Characters must summon the courage to confront their fears and break free from the chains of bondage.", category: "act2"),
            TarotCard(name: "the Tower", imageName: "act9", description: "In the second act, characters navigate a period of chaos and reckoning as they come to terms with the consequences of The Tower's destruction. They confront their own vulnerabilities and limitations, as well as the flaws and shortcomings of the systems and structures that once provided security.", category: "act2"),
            TarotCard(name: "the Sun", imageName: "act11", description: "In the second act, characters experience a period of growth and expansion as they align with the energy of The Sun. They embrace new opportunities and possibilities, feeling empowered to pursue their dreams and aspirations with passion and determination. Characters radiate with confidence and self-assurance as they step into the fullness of their potential, embracing the abundance and prosperity that comes with aligning with The Sun's energy.", category: "act2"),
            TarotCard(name: "the Judgment", imageName: "act13", description: "In the second act, characters undergo a process of redemption and forgiveness as they confront their past mistakes and shortcomings. They are offered the opportunity for spiritual renewal and rebirth, as they release old patterns and embrace a new sense of purpose and direction.", category: "act2"),
            
            
            TarotCard(name: "the Lovers", imageName: "act1", description: "In the final act, the Lovers come to a resolution, finding harmony and unity in their relationship. Through honesty, communication, and mutual understanding, they are able to overcome the conflicts that once threatened to drive them apart. Their love is reaffirmed, and they embark on a new chapter together, strengthened by the trials they've overcome and the deep connection they share.", category: "act3"),
            TarotCard(name: "the Chariot", imageName: "act2", description: "In the final act, characters experience triumph and victory as they overcome the challenges and obstacles in their path. They emerge victorious, having conquered their fears and doubts through sheer determination and willpower. Characters embrace their inner strength and celebrate their achievements. The Chariot represents a journey of self-discovery and empowerment, where characters drive to achieve success and fulfillment in their lives.", category: "act3"),
            TarotCard(name: "Strenght", imageName: "act3", description: "In the final act, characters embrace their inner strength and emerge transformed by their journey. They have faced their fears and conquered their doubts, emerging stronger and more resilient than ever before. Characters embrace their true selves, embracing their vulnerabilities and embracing their strengths. ", category: "act3"),
            TarotCard(name: "the Wheel of Fortune", imageName: "act4", description: "In the final act, characters come to accept the cyclical nature of the wheel and embrace the changes it brings. They recognize that life is a journey of constant transformation, and they learn to surrender to the flow of destiny. Characters find peace and fulfillment in the knowledge that, no matter what challenges may arise, they have the strength and resilience to face them head-on.", category: "act3"),
            TarotCard(name: "the Justice", imageName: "act5", description: "In the final act, characters experience a process of rebirth and renewal as they emerge from the ashes of The Tower's destruction. They find strength and resilience in the face of adversity, discovering new opportunities for growth and transformation amidst the chaos. Characters embrace the opportunity for change and reinvention, forging a path forward that is stronger and more resilient than before.", category: "act3"),
            TarotCard(name: "Death", imageName: "act7", description: "In the final act, characters fully embrace the transformative power of Death. They emerge from the crucible of change reborn, with a newfound sense of purpose and clarity. Characters embrace the inevitability of change and learn to embrace the uncertainty of the future. They recognize that death is not an end, but rather a transition to something new and unknown.", category: "act3"),
            TarotCard(name: "the Tower", imageName: "act9", description: "In the final act, characters experience a process of rebirth and renewal as they emerge from the ashes of The Tower's destruction. They find strength and resilience in the face of adversity, discovering new opportunities for growth and transformation amidst the chaos. Characters embrace the opportunity for change and reinvention, forging a path forward that is stronger and more resilient than before. ", category: "act3"),
            TarotCard(name: "the Star", imageName: "act10", description: "In the final act, characters receive guidance and fulfillment as they align with the energy of The Star. They find themselves guided by a sense of purpose and direction, as they follow the light of The Star towards their destiny. Characters experience a sense of fulfillment and joy as they embrace their true path and pursue their dreams with confidence and determination.", category: "act3"),
            TarotCard(name: "the Sun", imageName: "act11", description: "In the final act, characters experience a sense of illumination and fulfillment as they bask in the light of The Sun. They feel a deep sense of contentment and joy as they embrace the blessings and abundance that surround them. Characters find themselves aligned with their true purpose and passion, living in harmony with the universe and experiencing a profound sense of fulfillment and satisfaction.", category: "act3"),
            TarotCard(name: "the Moon", imageName: "act12", description: "In the final act, characters emerge from The Moon's realm transformed by their journey through the darkness. They have confronted their fears and illusions, emerging with a newfound sense of clarity and understanding. Characters integrate the lessons they have learned into their lives, embracing their inner wisdom and intuition as they move forward on their journey.", category: "act3"),
            TarotCard(name: "the Judgment", imageName: "act13", description: "In the final act, characters experience a profound transformation and liberation as they embrace the lessons of Judgment and emerge reborn. They have undergone a process of spiritual awakening and renewal, shedding old identities and beliefs that no longer serve them. Characters step into their true power and potential, ready to embark on a new chapter of their lives with clarity and purpose.", category: "act3"),
            TarotCard(name: "the World", imageName: "act14", description: "In the final act, characters experience a profound sense of completion and fulfillment as they align with the energy of The World. They have reached the culmination of their journey, having overcome obstacles and challenges to achieve their goals. Characters bask in the glow of success and achievement, feeling a deep sense of satisfaction and contentment as they embrace the fullness of life's blessings.", category: "act3")
        ]
    }
}
